set_property SRC_FILE_INFO {cfile:C:/Users/Bardi/Desktop/VHDL_TETRIS/Nexys-A7-100T-Master.xdc rfile:../../../../Nexys-A7-100T-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E3    IOSTANDARD LVCMOS33 } [get_ports { CLK_I }]; IO_L12P_T1_MRCC_35 Sch=CLK_I
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A3    IOSTANDARD LVCMOS33 } [get_ports { VGA_RED_O[0] }]; IO_L8N_T1_AD14N_35 Sch=VGA_RED_O[0]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B4    IOSTANDARD LVCMOS33 } [get_ports { VGA_RED_O[1] }]; IO_L7N_T1_AD6N_35 Sch=VGA_RED_O[1]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C5    IOSTANDARD LVCMOS33 } [get_ports { VGA_RED_O[2] }]; IO_L1N_T0_AD4N_35 Sch=VGA_RED_O[2]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A4    IOSTANDARD LVCMOS33 } [get_ports { VGA_RED_O[3] }]; IO_L8P_T1_AD14P_35 Sch=VGA_RED_O[3]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C6    IOSTANDARD LVCMOS33 } [get_ports { VGA_GREEN_O[0] }]; IO_L1P_T0_AD4P_35 Sch=VGA_GREEN_O[0]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A5    IOSTANDARD LVCMOS33 } [get_ports { VGA_GREEN_O[1] }]; IO_L3N_T0_DQS_AD5N_35 Sch=VGA_GREEN_O[1]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B6    IOSTANDARD LVCMOS33 } [get_ports { VGA_GREEN_O[2] }]; IO_L2N_T0_AD12N_35 Sch=VGA_GREEN_O[2]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A6    IOSTANDARD LVCMOS33 } [get_ports { VGA_GREEN_O[3] }]; IO_L3P_T0_DQS_AD5P_35 Sch=VGA_GREEN_O[3]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B7    IOSTANDARD LVCMOS33 } [get_ports { VGA_BLUE_O[0] }]; IO_L2P_T0_AD12P_35 Sch=VGA_BLUE_O[0]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C7    IOSTANDARD LVCMOS33 } [get_ports { VGA_BLUE_O[1] }]; IO_L4N_T0_35 Sch=VGA_BLUE_O[1]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D7    IOSTANDARD LVCMOS33 } [get_ports { VGA_BLUE_O[2] }]; IO_L6N_T0_VREF_35 Sch=VGA_BLUE_O[2]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D8    IOSTANDARD LVCMOS33 } [get_ports { VGA_BLUE_O[3] }]; IO_L4P_T0_35 Sch=VGA_BLUE_O[3]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B11   IOSTANDARD LVCMOS33 } [get_ports { VGA_HS_O }]; IO_L4P_T0_15 Sch=VGA_HS_O
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B12   IOSTANDARD LVCMOS33 } [get_ports { VGA_VS_O }]; IO_L3N_T0_DQS_AD1N_15 Sch=VGA_VS_O
