# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Bardi/Desktop/VHDL_TETRIS/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/Bardi/Desktop/VHDL_TETRIS/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/Bardi/Desktop/VHDL_TETRIS/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/Bardi/Desktop/VHDL_TETRIS/project_1/project_1.srcs/sources_1/new/MAIN.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Bardi/Desktop/VHDL_TETRIS/Nexys-A7-100T-Master.xdc
set_property used_in_implementation false [get_files C:/Users/Bardi/Desktop/VHDL_TETRIS/Nexys-A7-100T-Master.xdc]


synth_design -top vga -part xc7a100tcsg324-1


write_checkpoint -force -noxdef vga.dcp

catch { report_utilization -file vga_utilization_synth.rpt -pb vga_utilization_synth.pb }
